runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --timeout 100 main:app

runtime_config:
  python_version: 3

service: textclassifier

skip_files:
  - ^\..*$

env_variables:
  GCS_BUCKET: "textclassifier"
  GCS_BLOB: "model.joblib"

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
